---
# file: roles/create_droplet/tasks/main.yml

- include_vars: "vars/main.yml"

# Create basic DigitalOcean droplet
- name: create DigitalOcean droplet
  digital_ocean_droplet: 
    name: mytest01
    oauth_token: "{{ DO_API_TOKEN }}"
    unique_name: "{{ do.unique_name }}"
    region: "{{ do.region }}"
    image: "{{ do.image }}"
    wait: "{{ do.wait }}"
    wait_timeout: "{{ do.wait_timeout }}"
    size_id: "{{ do.size_id }}"
    state: "{{ do.state }}"
    ssh_keys: "{{ do.ssh_keys }}"
    ipv6: "{{ do.ipv6 }}"
    private_networking: "{{ do.private_networking }}"
    monitoring: "{{ do.monitoring }}"
    backups: "{{ do.backups }}"
  register: mytest01

- name: create DigitalOcean tag
  digital_ocean_tag:
    name: test
    oauth_token: "{{ DO_API_TOKEN }}"
    resource_id: "{{ mytest01.data.droplet.id }}"
    state: present
  register: tag_response

- name: add hosts
  add_host:
    name: "{{ mytest01.data.ip_address }}"
    groups: "do"

- debug:
    msg: "ID is {{ mytest01.data.droplet.id }}, IP is {{ mytest01.data.ip_address }}"