---

create_user: ceyounger
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']
unique_name: yes
region: sfo2
image: ubuntu-18-04-x64
wait: yes
wait_timeout: 500
size_id: s-1vcpu-1gb
state: present
ssh_keys: [ '113055', '26017821', '26017817', '26017805', '26017812', '26017803', '26017837' ]
ipv6: yes
private_networking: no
monitoring: yes
backups: no