---
# file: roles/common/tasks/cockpit-redhat.yml
- name: Install Cockpit
    yum: name=cockpit state=present
  notify: 
    - Start Cockpit
  tags: cockpit

- name: Enable Cockpit in systemd
  systemd: name=cockpit.socket enabled=true
  when: ansible_distribution == "CentOS"
  tags: cockpit

- name: Check state of firewalld and register
  command: /usr/bin/firewall-cmd --state
  ignore_errors: yes
  register: firewalld_state
  when: ansible_distribution == "CentOS"
  tags: cockpit

- name: Modify firewalld
  firewalld: service=cockpit zone=public permanent=true immediate=yes state=enabled offline=true
  when: 
    - ansible_distribution == "CentOS"
    - firewalld_state == "running"
  tags: cockpit