---
# file: roles/common/tasks/cockpit-debian.yml
- name: Install Cockpit
  apt: name=cockpit state=installed update_cache=true
  notify: 
    - Start Cockpit
  tags: cockpit

- name: Check state of UFW and register
  command: "ufw status | grep Status: | sed 's/Status: //g'"
  register: ufw_state
  when: ansible_distribution == "Ubuntu"
  tags: cockpit

- name: Modify UFW
  ufw: rule=allow port=9090 proto=tcp src={{ item }}
  with_items:
    - 192.168.52.0/24
    - 192.168.250.0/24
    - 172.16.0.0/12
  when: 
    - ansible_distribution == "Ubuntu"
    - ufw_state = "active"
  tags: cockpit