---
# file: roles/common/tasks/webmin-debian.yml
- name: Add Webmin Key for Ubuntu
  apt_key: url=http://www.webmin.com/jcameron-key.asc state=present
  when: ansible_distribution == "Ubuntu"
  tags: webmin
  
- name: Add Webmin APT Repo for Ubuntu  
  apt_repository:
    repo: deb https://download.webmin.com/download/repository sarge contrib
    state: present
    filename: 'webmin'
  when: ansible_distribution == "Ubuntu"
  tags: webmin

- name: Install HTTPS support for APT on Ubuntu
  apt: name=apt-transport-https state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"
  tags: webmin

- name: Install Webmin
  apt: name=webmin state=present update_cache=true
  notify: Start Webmin
  tags: webmin

- name: Check state of UFW and register
  command: "ufw status | grep Status: | sed 's/Status: //g'"
  register: ufw_state
  when: ansible_distribution == "Ubuntu"
  tags: webmin

- name: Modify UFW
  ufw: rule=allow port=10000 proto=tcp src={{ item }}
  with_items:
    - 192.168.52.0/24
    - 192.168.250.0/24
    - 172.16.0.0/12
  when: 
    - ansible_distribution =="Ubuntu"
    - ufw_state == "active"
  tags: webmin